### PR TITLE
Allow writing null values when using indirect method

### PR DESCRIPTION
**Pull request by jphalip**

### CODE REVIEW

**Comment by yigress** [comment]
I think it is okay to commit this in at this time. we can add `not null` support later.

**Comment by yigress** [comment]
can you clarify the following scenario:
if it is external table, bq table have not null constraint on a column, what happens? does query fails at later stage when try to load into bq table?

**Comment by jphalip** [comment]
Yes, ultimately BigQuery would enforce NOT NULL constraints. This PR is to relax Avro's enforcement since we're only using Avro for transport.

Regarding the test, do you know why we can't set NULL for TIMESTAMPTZ, MAP, etc? If you set those values to NULL then Hive complains with an error.

**Comment by yigress** [comment]
can we add test for this scenario:
1. hive managed table is created with not null on a column
2. verify that query will fail.

this is different from hive external table.

**Comment by yigress** [comment]
> Yes, ultimately BigQuery would enforce NOT NULL constraints. This PR is to relax Avro's enforcement since we're only using Avro for transport.
> 
> Regarding the test, do you know why we can't set NULL for TIMESTAMPTZ, MAP, etc? If you set those values to NULL then Hive complains with an error.

timestamptz not accepting null (void) due to this
https://github.com/apache/hive/blob/master/ql/src/java/org/apache/hadoop/hive/ql/udf/generic/GenericUDFToTimestampLocalTZ.java#L60

**Comment by jphalip** [comment]
Ok and I assume the same for MAP, STRUCT, DECIMAL, and ARRAY?

**Comment by jphalip** [comment]
I suggest we tackle the NOT NULL issue separately. What do you think?

**Comment by yigress** [comment]
LGTM + 1

**Pull request merged**
